/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ts-animation.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../turingmachineservice.service';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './ts-animation.component.css.shim';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/ng_model';
import * as import15 from '@angular/forms/src/directives/ng_control_status';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/ng_control';
var renderType_TsAnimationComponent_Host:import0.RenderComponentType = (null as any);
class _View_TsAnimationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TsAnimationComponent_0_4:import3.TsAnimationComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TsAnimationComponent_Host0,renderType_TsAnimationComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ts-animation',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TsAnimationComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TsAnimationComponent_0_4 = new import3.TsAnimationComponent(this.parentInjector.get(import8.TuringmachineService),this.parentInjector.get(import9.NgZone));
    this._appEl_0.initComponent(this._TsAnimationComponent_0_4,[],compView_0);
    compView_0.create(this._TsAnimationComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TsAnimationComponent) && (0 === requestNodeIndex))) { return this._TsAnimationComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TsAnimationComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TsAnimationComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TsAnimationComponent_Host === (null as any))) { (renderType_TsAnimationComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_TsAnimationComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TsAnimationComponentNgFactory:import11.ComponentFactory<import3.TsAnimationComponent> = new import11.ComponentFactory<import3.TsAnimationComponent>('ts-animation',viewFactory_TsAnimationComponent_Host0,import3.TsAnimationComponent);
const styles_TsAnimationComponent:any[] = [import12.styles];
var renderType_TsAnimationComponent:import0.RenderComponentType = (null as any);
class _View_TsAnimationComponent0 extends import1.AppView<import3.TsAnimationComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _DefaultValueAccessor_43_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_43_4:any[];
  _NgModel_43_5:import14.NgModel;
  _NgControl_43_6:any;
  _NgControlStatus_43_7:import15.NgControlStatus;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TsAnimationComponent0,renderType_TsAnimationComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-3');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','gridHeader');
    this._el_3 = this.renderer.createElement(this._el_2,'b',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','col-md-6');
    this._text_8 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','gridHeader');
    this._el_10 = this.renderer.createElement(this._el_9,'b',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'ExampleName',(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','col-md-3');
    this._text_15 = this.renderer.createText(this._el_14,'\n  ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','gridHeader');
    this._el_17 = this.renderer.createElement(this._el_16,'b',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_14,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_21 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','col-md-12');
    this.renderer.setElementAttribute(this._el_21,'style','padding:0;');
    this._text_22 = this.renderer.createText(this._el_21,'\n  ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'id','canvasWidth');
    this._text_24 = this.renderer.createText(this._el_23,'\n  ',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_27 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','col-md-12');
    this._text_28 = this.renderer.createText(this._el_27,'\n  ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_29,'style','text-align: left;');
    this._el_30 = this.renderer.createElement(this._el_29,'b',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Console',(null as any));
    this._text_32 = this.renderer.createText(this._el_27,'\n  ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','panel panel-default');
    this._text_34 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_35,'id','consoleCM');
    this.renderer.setElementAttribute(this._el_35,'style','display: none; height:50px;');
    this._text_36 = this.renderer.createText(this._el_33,'\n  ',(null as any));
    this._text_37 = this.renderer.createText(this._el_27,'\n',(null as any));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_39 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','col-md-4');
    this._text_40 = this.renderer.createText(this._el_39,'\n\n  ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','input-group form-group-lg max');
    this.renderer.setElementAttribute(this._el_41,'style','  padding-bottom: 3%; margin-left: auto; margin-right: auto;');
    this._text_42 = this.renderer.createText(this._el_41,'\n    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'input',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','form-control');
    this.renderer.setElementAttribute(this._el_43,'placeholder','Input');
    this.renderer.setElementAttribute(this._el_43,'type','text');
    this._DefaultValueAccessor_43_3 = new import13.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_43));
    this._NG_VALUE_ACCESSOR_43_4 = [this._DefaultValueAccessor_43_3];
    this._NgModel_43_5 = new import14.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_43_4);
    this._NgControl_43_6 = this._NgModel_43_5;
    this._NgControlStatus_43_7 = new import15.NgControlStatus(this._NgControl_43_6);
    this._text_44 = this.renderer.createText(this._el_41,'\n    ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_41,'span',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','input-group-btn');
    this._text_46 = this.renderer.createText(this._el_45,'\n              ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','btn btn-lg btn-primary btn-block');
    this.renderer.setElementAttribute(this._el_47,'type','button');
    this._text_48 = this.renderer.createText(this._el_47,'Input',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._text_50 = this.renderer.createText(this._el_41,'\n\n  ',(null as any));
    this._text_51 = this.renderer.createText(this._el_39,'\n\n',(null as any));
    this._text_52 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_53 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','col-md-4');
    this._text_54 = this.renderer.createText(this._el_53,'\n  ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','text-center');
    this._text_56 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'div',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','btn-group btn-group-lg');
    this._text_58 = this.renderer.createText(this._el_57,'\n      ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'button',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_59,'type','button');
    this._el_60 = this.renderer.createElement(this._el_59,'span',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','glyphicon glyphicon-play');
    this._text_61 = this.renderer.createText(this._el_57,'\n      ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_57,'button',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_62,'type','button');
    this._el_63 = this.renderer.createElement(this._el_62,'span',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','glyphicon glyphicon-pause');
    this._text_64 = this.renderer.createText(this._el_57,'\n      ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_57,'button',(null as any));
    this.renderer.setElementAttribute(this._el_65,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_65,'type','button');
    this._el_66 = this.renderer.createElement(this._el_65,'span',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','glyphicon glyphicon-stop');
    this._text_67 = this.renderer.createText(this._el_57,'\n      ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_57,'button',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_68,'type','button');
    this._el_69 = this.renderer.createElement(this._el_68,'span',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','glyphicon glyphicon-step-forward');
    this._text_70 = this.renderer.createText(this._el_57,'\n    ',(null as any));
    this._text_71 = this.renderer.createText(this._el_55,'\n  ',(null as any));
    this._text_72 = this.renderer.createText(this._el_53,'\n\n',(null as any));
    this._text_73 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_74 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','col-md-4');
    this._text_75 = this.renderer.createText(this._el_74,'\n  ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'div',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','row');
    this.renderer.setElementAttribute(this._el_76,'style','margin: 0px;');
    this._text_77 = this.renderer.createText(this._el_76,'\n    ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_76,'div',(null as any));
    this.renderer.setElementAttribute(this._el_78,'class','col-md-5');
    this._text_79 = this.renderer.createText(this._el_78,'\n      ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_78,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','gridHeader');
    this.renderer.setElementAttribute(this._el_80,'style','float: right;');
    this._el_81 = this.renderer.createElement(this._el_80,'b',(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Speed: ',(null as any));
    this._text_83 = this.renderer.createText(this._el_78,'\n    ',(null as any));
    this._text_84 = this.renderer.createText(this._el_76,'\n    ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_76,'div',(null as any));
    this.renderer.setElementAttribute(this._el_85,'class','col-md-7');
    this._text_86 = this.renderer.createText(this._el_85,'\n      ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_85,'div',(null as any));
    this.renderer.setElementAttribute(this._el_87,'id','slider');
    this.renderer.setElementAttribute(this._el_87,'style',' margin-bottom:10px; margin-top:10px;');
    this._text_88 = this.renderer.createText(this._el_87,'\n      ',(null as any));
    this._text_89 = this.renderer.createText(this._el_85,'\n    ',(null as any));
    this._text_90 = this.renderer.createText(this._el_76,'\n  ',(null as any));
    this._text_91 = this.renderer.createText(this._el_74,'\n',(null as any));
    this._text_92 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_43,'ngModelChange',this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_43,'input',this.eventHandler(this._handle_input_43_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_43,'blur',this.eventHandler(this._handle_blur_43_2.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_43_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_59,'click',this.eventHandler(this._handle_click_59_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_62,'click',this.eventHandler(this._handle_click_62_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_65,'click',this.eventHandler(this._handle_click_65_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultValueAccessor) && (43 === requestNodeIndex))) { return this._DefaultValueAccessor_43_3; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_4; }
    if (((token === import14.NgModel) && (43 === requestNodeIndex))) { return this._NgModel_43_5; }
    if (((token === import18.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_6; }
    if (((token === import15.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_5:any = this.context.inputData;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgModel_43_5.model = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._NgModel_43_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'Steps: ',this.context._counter,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_4,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'State: ',this.context._state,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_18,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_6:any = this._NgControlStatus_43_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_43,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_43_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_43,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_43_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_43,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_43_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_43,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_43_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_43,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_43_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_43,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = this.context.inputBtnNotVisible;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementProperty(this._el_47,'disabled',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = (this.context.isPlayBtnVisible || (this.context.input === ''));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementProperty(this._el_59,'disabled',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = (this.context.isPlayBtnVisible || (this.context.input === ''));
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementProperty(this._el_62,'disabled',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = (this.context.isPlayBtnVisible || (this.context.input === ''));
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementProperty(this._el_65,'disabled',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = (this.context.isPlayBtnVisible || (this.context.input === ''));
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementProperty(this._el_68,'disabled',currVal_20);
      this._expr_20 = currVal_20;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_43_5.ngOnDestroy();
  }
  private _handle_ngModelChange_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.inputData = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_43_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_43_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_43_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_43_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadInputData(this.context.inputData)) !== false);
    return (true && pd_0);
  }
  private _handle_click_59_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.play()) !== false);
    return (true && pd_0);
  }
  private _handle_click_62_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pause()) !== false);
    return (true && pd_0);
  }
  private _handle_click_65_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.clear()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TsAnimationComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TsAnimationComponent> {
  if ((renderType_TsAnimationComponent === (null as any))) { (renderType_TsAnimationComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_TsAnimationComponent,{})); }
  return new _View_TsAnimationComponent0(viewUtils,parentInjector,declarationEl);
}