/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './turing-machine.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../turingmachineservice.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './turing-machine.component.css.shim';
import * as import12 from './ts-animation/ts-animation.component';
import * as import13 from './load-example/load-example.component';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from './editor/editor.component';
import * as import18 from './chart/chart.component';
import * as import19 from './ts-animation/ts-animation.component.ngfactory';
import * as import20 from '@angular/core/src/zone/ng_zone';
import * as import21 from './load-example/load-example.component.ngfactory';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from './editor/editor.component.ngfactory';
import * as import24 from './chart/chart.component.ngfactory';
import * as import25 from '@angular/forms/src/directives/control_container';
var renderType_TuringMachineComponent_Host:import0.RenderComponentType = (null as any);
class _View_TuringMachineComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TuringMachineComponent_0_4:import3.TuringMachineComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TuringMachineComponent_Host0,renderType_TuringMachineComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-turing-machine',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TuringMachineComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TuringMachineComponent_0_4 = new import3.TuringMachineComponent(this.parentInjector.get(import8.TuringmachineService));
    this._appEl_0.initComponent(this._TuringMachineComponent_0_4,[],compView_0);
    compView_0.create(this._TuringMachineComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TuringMachineComponent) && (0 === requestNodeIndex))) { return this._TuringMachineComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._TuringMachineComponent_0_4.ngAfterViewInit(); } }
  }
}
function viewFactory_TuringMachineComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TuringMachineComponent_Host === (null as any))) { (renderType_TuringMachineComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_TuringMachineComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TuringMachineComponentNgFactory:import10.ComponentFactory<import3.TuringMachineComponent> = new import10.ComponentFactory<import3.TuringMachineComponent>('app-turing-machine',viewFactory_TuringMachineComponent_Host0,import3.TuringMachineComponent);
const styles_TuringMachineComponent:any[] = [import11.styles];
var renderType_TuringMachineComponent:import0.RenderComponentType = (null as any);
class _View_TuringMachineComponent0 extends import1.AppView<import3.TuringMachineComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TsAnimationComponent_14_4:import12.TsAnimationComponent;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _LoadExampleComponent_21_4:import13.LoadExampleComponent;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import14.NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import14.NgIf;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import14.NgIf;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _NgForm_50_3:import15.NgForm;
  _ControlContainer_50_4:any;
  _NgControlStatusGroup_50_5:import16.NgControlStatusGroup;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import2.AppElement;
  _EditorComponent_54_4:import17.EditorComponent;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  /*private*/ _appEl_64:import2.AppElement;
  _ChartComponent_64_4:import18.ChartComponent;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _el_72:any;
  _el_73:any;
  _text_74:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TuringMachineComponent0,renderType_TuringMachineComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'header',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','jumbotron');
    this.renderer.setElementAttribute(this._el_3,'style','background-color: #ffffff; padding: 0;');
    this._text_4 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_5,'style','text-align: center;');
    this._text_6 = this.renderer.createText(this._el_5,'TURINGMACHINE',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'id','container4');
    this._text_11 = this.renderer.createText(this._el_10,'\n\n  ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','row well');
    this.renderer.setElementAttribute(this._el_12,'style','padding:0;');
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ts-animation',(null as any));
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import19.viewFactory_TsAnimationComponent0(this.viewUtils,this.injector(14),this._appEl_14);
    this._TsAnimationComponent_14_4 = new import12.TsAnimationComponent(this.parentInjector.get(import8.TuringmachineService),this.parentInjector.get(import20.NgZone));
    this._appEl_14.initComponent(this._TsAnimationComponent_14_4,[],compView_14);
    compView_14.create(this._TsAnimationComponent_14_4,[],(null as any));
    this._text_15 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n  ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','row');
    this._text_18 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','col-md-12');
    this.renderer.setElementAttribute(this._el_19,'style','text-align:center;');
    this._text_20 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'load-example',(null as any));
    this._appEl_21 = new import2.AppElement(21,19,this,this._el_21);
    var compView_21:any = import21.viewFactory_LoadExampleComponent0(this.viewUtils,this.injector(21),this._appEl_21);
    this._LoadExampleComponent_21_4 = new import13.LoadExampleComponent();
    this._appEl_21.initComponent(this._LoadExampleComponent_21_4,[],compView_21);
    compView_21.create(this._LoadExampleComponent_21_4,[],(null as any));
    this._text_22 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_17,'\n\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','col-md-12');
    this.renderer.setElementAttribute(this._el_24,'style','margin-top:0.5%;');
    this._text_25 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_26 = new import2.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import22.TemplateRef_(this._appEl_26,viewFactory_TuringMachineComponent1);
    this._NgIf_26_6 = new import14.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_24,'\n\n      ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_28 = new import2.AppElement(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import22.TemplateRef_(this._appEl_28,viewFactory_TuringMachineComponent2);
    this._NgIf_28_6 = new import14.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_30 = new import2.AppElement(30,24,this,this._anchor_30);
    this._TemplateRef_30_5 = new import22.TemplateRef_(this._appEl_30,viewFactory_TuringMachineComponent3);
    this._NgIf_30_6 = new import14.NgIf(this._appEl_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_17,'\n\n\n    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','col-md-12');
    this.renderer.setElementAttribute(this._el_33,'style','padding:0;');
    this._text_34 = this.renderer.createText(this._el_33,'\n\n      ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','nav nav-tabs');
    this.renderer.setElementAttribute(this._el_35,'style','margin-bottom: 0;');
    this._text_36 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'li',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','active');
    this._el_38 = this.renderer.createElement(this._el_37,'a',(null as any));
    this.renderer.setElementAttribute(this._el_38,'data-toggle','tab');
    this.renderer.setElementAttribute(this._el_38,'href','#editor');
    this._text_39 = this.renderer.createText(this._el_38,'Editor',(null as any));
    this._text_40 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_35,'li',(null as any));
    this._el_42 = this.renderer.createElement(this._el_41,'a',(null as any));
    this.renderer.setElementAttribute(this._el_42,'data-toggle','tab');
    this.renderer.setElementAttribute(this._el_42,'href','#statistic');
    this._text_43 = this.renderer.createText(this._el_42,'State Diagram',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._text_45 = this.renderer.createText(this._el_33,'\n\n      ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','tab-content');
    this.renderer.setElementAttribute(this._el_46,'style','border-left: 1px solid #ddd;\n    border-right: 1px solid #ddd;\n    border-bottom: 1px solid #ddd;\n    padding: 10px;\n    border-radius: 0px 0px 5px 5px;\n    ');
    this._text_47 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','tab-pane fade in active');
    this.renderer.setElementAttribute(this._el_48,'id','editor');
    this._text_49 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'form',(null as any));
    this._NgForm_50_3 = new import15.NgForm((null as any),(null as any));
    this._ControlContainer_50_4 = this._NgForm_50_3;
    this._NgControlStatusGroup_50_5 = new import16.NgControlStatusGroup(this._ControlContainer_50_4);
    this._text_51 = this.renderer.createText(this._el_50,'\n          ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'div',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','panel panel-default');
    this.renderer.setElementAttribute(this._el_52,'style',' margin: auto; width:68%; margin-top: 2%; margin-bottom:0;');
    this._text_53 = this.renderer.createText(this._el_52,'\n            ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'ts-editor',(null as any));
    this._appEl_54 = new import2.AppElement(54,52,this,this._el_54);
    var compView_54:any = import23.viewFactory_EditorComponent0(this.viewUtils,this.injector(54),this._appEl_54);
    this._EditorComponent_54_4 = new import17.EditorComponent(this.parentInjector.get(import8.TuringmachineService));
    this._appEl_54.initComponent(this._EditorComponent_54_4,[],compView_54);
    compView_54.create(this._EditorComponent_54_4,[],(null as any));
    this._text_55 = this.renderer.createText(this._el_52,'\n          ',(null as any));
    this._text_56 = this.renderer.createText(this._el_50,'\n\n          ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_50,'button',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','btn btn-primary btn-lg btn-block');
    this.renderer.setElementAttribute(this._el_57,'style','width: 68%; margin:auto;');
    this.renderer.setElementAttribute(this._el_57,'type','button');
    this._text_58 = this.renderer.createText(this._el_57,'Compile',(null as any));
    this._text_59 = this.renderer.createText(this._el_50,'\n          ',(null as any));
    this._text_60 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_46,'div',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','tab-pane fade');
    this.renderer.setElementAttribute(this._el_62,'id','statistic');
    this._text_63 = this.renderer.createText(this._el_62,'\n          ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_62,'ts-chart',(null as any));
    this._appEl_64 = new import2.AppElement(64,62,this,this._el_64);
    var compView_64:any = import24.viewFactory_ChartComponent0(this.viewUtils,this.injector(64),this._appEl_64);
    this._ChartComponent_64_4 = new import18.ChartComponent();
    this._appEl_64.initComponent(this._ChartComponent_64_4,[],compView_64);
    compView_64.create(this._ChartComponent_64_4,[],(null as any));
    this._text_65 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._text_66 = this.renderer.createText(this._el_46,'\n\n      ',(null as any));
    this._text_67 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._text_68 = this.renderer.createText(this._el_17,'\n\n  ',(null as any));
    this._text_69 = this.renderer.createText(this._el_10,'\n\n\n',(null as any));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n',(null as any));
    this._el_71 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_72 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_73 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_74 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_14,'eventStateDiagram',this.eventHandler(this._handle_eventStateDiagram_14_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_14,'eventWordStatus',this.eventHandler(this._handle_eventWordStatus_14_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._TsAnimationComponent_14_4.eventWordStatus.subscribe(this.eventHandler(this._handle_eventWordStatus_14_1.bind(this)));
    const subscription_1:any = this._TsAnimationComponent_14_4.eventStateDiagram.subscribe(this.eventHandler(this._handle_eventStateDiagram_14_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_21,'onLoaded',this.eventHandler(this._handle_onLoaded_21_0.bind(this)));
    const subscription_2:any = this._LoadExampleComponent_21_4.onLoaded.subscribe(this.eventHandler(this._handle_onLoaded_21_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_50,'submit',this.eventHandler(this._handle_submit_50_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_50,'reset',this.eventHandler(this._handle_reset_50_1.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_54,'codeChanges',this.eventHandler(this._handle_codeChanges_54_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    const subscription_3:any = this._EditorComponent_54_4.codeChanges.subscribe(this.eventHandler(this._handle_codeChanges_54_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_57,'click',this.eventHandler(this._handle_click_57_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._el_72,
      this._el_73,
      this._text_74
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TsAnimationComponent) && (14 === requestNodeIndex))) { return this._TsAnimationComponent_14_4; }
    if (((token === import13.LoadExampleComponent) && (21 === requestNodeIndex))) { return this._LoadExampleComponent_21_4; }
    if (((token === import22.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import14.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    if (((token === import22.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import14.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    if (((token === import22.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import14.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6; }
    if (((token === import17.EditorComponent) && (54 === requestNodeIndex))) { return this._EditorComponent_54_4; }
    if (((token === import15.NgForm) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgForm_50_3; }
    if (((token === import25.ControlContainer) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._ControlContainer_50_4; }
    if (((token === import16.NgControlStatusGroup) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgControlStatusGroup_50_5; }
    if (((token === import18.ChartComponent) && (64 === requestNodeIndex))) { return this._ChartComponent_64_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_2:any = this.context.isPlayBtnVisible;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._TsAnimationComponent_14_4.isPlayBtnVisible = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TsAnimationComponent_14_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._LoadExampleComponent_21_4.ngOnInit(); }
    const currVal_4:any = this.context.isCompileError;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_26_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.isFail;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_28_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.isSuccess;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_30_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    changes = (null as any);
    const currVal_16:any = this.context.exampleCode;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._EditorComponent_54_4.exampleData = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['exampleData'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    if ((changes !== (null as any))) { this._EditorComponent_54_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._EditorComponent_54_4.ngOnInit(); }
    changes = (null as any);
    const currVal_18:any = this.context.stateDiagram;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._ChartComponent_64_4.stateDiagram = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['stateDiagram'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    if ((changes !== (null as any))) { this._ChartComponent_64_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ChartComponent_64_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_9:any = this._NgControlStatusGroup_50_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_50,'ng-untouched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_50_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_50,'ng-touched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_50_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_50,'ng-pristine',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_50_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_50,'ng-dirty',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_50_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_50,'ng-valid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatusGroup_50_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_50,'ng-invalid',currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_eventStateDiagram_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.setStateDiagram($event)) !== false);
    return (true && pd_0);
  }
  private _handle_eventWordStatus_14_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.setWordStatus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_onLoaded_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.setExample($event)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_50_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_50_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_50_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_codeChanges_54_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.codeChange($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_57_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.compile()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TuringMachineComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TuringMachineComponent> {
  if ((renderType_TuringMachineComponent === (null as any))) { (renderType_TuringMachineComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_TuringMachineComponent,{})); }
  return new _View_TuringMachineComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TuringMachineComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TuringMachineComponent1,renderType_TuringMachineComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this.renderer.setElementAttribute(this._el_0,'role','alert');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.errorMessage,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TuringMachineComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TuringMachineComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_TuringMachineComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TuringMachineComponent2,renderType_TuringMachineComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'\n        Not working!\n      ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_TuringMachineComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TuringMachineComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_TuringMachineComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TuringMachineComponent3,renderType_TuringMachineComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-success');
    this._text_1 = this.renderer.createText(this._el_0,'\n        Success!\n      ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_TuringMachineComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TuringMachineComponent3(viewUtils,parentInjector,declarationEl);
}