/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './load-example.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './load-example.component.css.shim';
var renderType_LoadExampleComponent_Host:import0.RenderComponentType = (null as any);
class _View_LoadExampleComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoadExampleComponent_0_4:import3.LoadExampleComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoadExampleComponent_Host0,renderType_LoadExampleComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('load-example',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoadExampleComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoadExampleComponent_0_4 = new import3.LoadExampleComponent();
    this._appEl_0.initComponent(this._LoadExampleComponent_0_4,[],compView_0);
    compView_0.create(this._LoadExampleComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoadExampleComponent) && (0 === requestNodeIndex))) { return this._LoadExampleComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._LoadExampleComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoadExampleComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoadExampleComponent_Host === (null as any))) { (renderType_LoadExampleComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_LoadExampleComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoadExampleComponentNgFactory:import9.ComponentFactory<import3.LoadExampleComponent> = new import9.ComponentFactory<import3.LoadExampleComponent>('load-example',viewFactory_LoadExampleComponent_Host0,import3.LoadExampleComponent);
const styles_LoadExampleComponent:any[] = [import10.styles];
var renderType_LoadExampleComponent:import0.RenderComponentType = (null as any);
class _View_LoadExampleComponent0 extends import1.AppView<import3.LoadExampleComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoadExampleComponent0,renderType_LoadExampleComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn-group btn-group-lg');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default dropdown-toggle');
    this.renderer.setElementAttribute(this._el_2,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_2,'type','button');
    this._text_3 = this.renderer.createText(this._el_2,'Example ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','caret');
    this._text_5 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','dropdown-menu');
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'li',(null as any));
    this._el_9 = this.renderer.createElement(this._el_8,'a',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Delete a',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_6,'li',(null as any));
    this._el_13 = this.renderer.createElement(this._el_12,'a',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Example2',(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_6,'li',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','divider');
    this._text_17 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_6,'li',(null as any));
    this._el_19 = this.renderer.createElement(this._el_18,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'href','#');
    this._text_20 = this.renderer.createText(this._el_19,'Example3',(null as any));
    this._text_21 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadExample('Example1')) !== false);
    return (true && pd_0);
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadExample('Example1')) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoadExampleComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoadExampleComponent> {
  if ((renderType_LoadExampleComponent === (null as any))) { (renderType_LoadExampleComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_LoadExampleComponent,{})); }
  return new _View_LoadExampleComponent0(viewUtils,parentInjector,declarationEl);
}